// comments sync
export const START_COMMENTS_SYNC_STARTED = 'START_COMMENTS_SYNC_STARTED'
export const START_COMMENTS_SYNC_SUCCESS = 'START_COMMENTS_SYNC_SUCCESS'
export const START_COMMENTS_SYNC_FAILURE = 'START_COMMENTS_SYNC_FAILURE'
export const STOP_COMMENTS_SYNC = 'STOP_COMMENTS_SYNC'
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS'

// comments manipulation
export const REMOVE_COMMENT_STARTED = 'REMOVE_COMMENT_STARTED'
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS'
export const REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE'
export const ADD_COMMENT_STARTED = 'ADD_COMMENT_STARTED'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

// post loading
export const LOAD_POSTS_STARTED = 'LOAD_POSTS_STARTED'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'
export const LOAD_POST_STARTED = 'LOAD_POST_STARTED'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

// like counter
export const INCREMENT_LIKES_STARTED = 'INCREMENT_LIKES_STARTED'
export const INCREMENT_LIKES_SUCCESS = 'INCREMENT_LIKES_SUCCESS'
export const INCREMENT_LIKES_NOT_COMMITTED = 'INCREMENT_LIKES_NOT_COMMITTED'
export const INCREMENT_LIKES_FAILURE = 'INCREMENT_LIKES_FAILURE'

// comments counter
export const INCREMENT_COMMENTS_STARTED = 'INCREMENT_COMMENTS_STARTED'
export const INCREMENT_COMMENTS_SUCCESS = 'INCREMENT_COMMENTS_SUCCESS'
export const INCREMENT_COMMENTS_NOT_COMMITTED = 
  'INCREMENT_COMMENTS_NOT_COMMITTED'
export const INCREMENT_COMMENTS_FAILURE = 'INCREMENT_COMMENTS_FAILURE'

// comments counter
export const DECREMENT_COMMENTS_STARTED = 'DECREMENT_COMMENTS_STARTED'
export const DECREMENT_COMMENTS_SUCCESS = 'DECREMENT_COMMENTS_SUCCESS'
export const DECREMENT_COMMENTS_NOT_COMMITTED = 
  'DECREMENT_COMMENTS_NOT_COMMITTED'
export const DECREMENT_COMMENTS_FAILURE = 'DECREMENT_COMMENTS_FAILURE'

// user
export const AUTHENTICATE_USER_STARTED = 'AUTHENTICATE_USER_STARTED'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'

export const LOGOUT_USER_STARTED = 'LOGOUT_USER_STARTED'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'
